export const countryList = [
  "ae",
  "ar",
  "at",
  "au",
  "be",
  "bg",
  "br",
  "ca",
  "ch",
  "cn",
  "co",
  "cu",
  "cz",
  "de",
  "eg",
  "fr",
  "gb",
  "gr",
  "hk",
  "hu",
  "id",
  "ie",
  "il",
  "in",
  "it",
  "jp",
  "kr",
  "lt",
  "lv",
  "ma",
  "mx",
  "my",
  "ng",
  "nl",
  "no",
  "nz",
  "ph",
  "pl",
  "pt",
  "ro",
  "rs",
  "ru",
  "sa",
  "se",
  "sg",
  "si",
  "sk",
  "th",
  "tr",
  "tw",
  "ua",
  "us",
  "ve",
  "za",
];

export const mockData = {
  source: {
    id: "t3n",
    name: "T3n",
  },
  author: "Dieter Petereit",
  title:
    "Euro und Dollar nur Bonbonpapier: Russland würde Bitcoin für Gaslieferungen akzeptieren",
  description:
    "Der oberste russische Energiebeauftragte Pawel Zavalny hat die Bereitschaft seines Landes erklärt, Bitcoin-Zah",
  url: "https://t3n.de/news/euro-dollar-nur-bonbonpapier-1461506/",
  urlToImage: "https://t3n.de/news/wp-content/uploads/2021/11/duma.jpg",
  publishedAt: "2022-03-24T17:06:25Z",
  content:
    "Pawel Zawalny ist Russlands Vorsitzender des Energieausschusses der Staatsduma. Der oberste Energiebeauftragte hat nun bestätigt, was westliche Politikerinnen wie die EZB-Präsidentin Christine Lagard… [+2175 chars]",
};
